//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApp.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Alumnos
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Alumnos()
        {
            this.Asistencia = new HashSet<Asistencia>();
            this.Historico_Cursos_Alumnos = new HashSet<Historico_Cursos_Alumnos>();
        }

        [Display(Name = "#")]
        public int id { get; set; }
                
        [Display(Name = "Nombre")]
        public string nombre_completo { get; set; }

        [Display(Name = "Cedula")]
        public string cedula { get; set; }

        [Display(Name = "Email")]
        public string email { get; set; }

        [Display(Name = "Departamento")]
        public string departamento { get; set; }

        [Display(Name = "Telefono")]
        public string telefono { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Asistencia> Asistencia { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Historico_Cursos_Alumnos> Historico_Cursos_Alumnos { get; set; }
    }
}
