//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Historico_Cursos_Alumnos
    {
        public int id { get; set; }
        public Nullable<int> id_alumno { get; set; }
        public Nullable<int> id_curso { get; set; }
        public Nullable<System.DateTime> fecha_registro { get; set; }
    
        public virtual Alumnos Alumnos { get; set; }
        public virtual Cursos Cursos { get; set; }
    }
}
